---

stages:
  - deploy


Install:
  stage: .pre
  image: node:alpine
  needs: []
  dependencies: []
  interruptible: true
  script:
    - npm install
  artifacts:
    paths:
      - nodes_modules/
      - .nuxt/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: node:alpine
  needs:
    - job: Install
      artifacts: true
  script:
    - npm install
    - npm run generate
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  environment:
    name: production
    url: https://hervaud.fr
    deployment_tier: production
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

...
