---
stages:
  - test
  - deploy

Install:
  stage: .pre
  image: node:alpine
  needs: []
  dependencies: []
  interruptible: true
  script:
    - npm install
  artifacts:
    paths:
      - nodes_modules/
      - .nuxt/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

# This job is used to let GitLab merge requests that have no job to be merged
# Fixing a weird behavior of GitLab, not letting you merge when your pipeline contains no job
No job MR validation:
  stage: test
  needs: []
  dependencies: []
  script:
    - echo "Skipping pipeline..."
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pages:
  stage: deploy
  image: node:alpine
  needs:
    - job: Install
      artifacts: true
  script:
    - npm install
    - npm run generate
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  environment:
    name: production
    url: https://hervaud.fr
    deployment_tier: production
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
