---
variables:
  HUSKY: 0

stages:
  - format
  - test
  - deploy

include:
  - component: gitlab.com/dependabot-gitlab/dependabot-standalone/template@3.15.0
    inputs:
      gitlab_access_token: $DEPENDABOT_GITLAB_ACCESS_TOKEN
      github_access_token: $DEPENDABOT_GITHUB_ACCESS_TOKEN
      stage_name: test
    rules:
      - if: $RUN_DEPENDABOT

cache:
  key:
    files:
      # - package-lock.json # BUG: Cannot use package-lock.json file as key because of this npm bug: https://github.com/npm/cli/issues/4828
      - package.json
  paths:
    # - node_modules/ # BUG: Cannot cache node modules because of this npm bug: https://github.com/npm/cli/issues/4828
    - .nuxt/
    - .npm/

Format code:
  stage: format
  image: node:alpine
  needs: []
  dependencies: []
  interruptible: true
  variables:
    COMMIT_MESSAGE: ":art: Format code"
    PUSH_BRANCH: $CI_COMMIT_BRANCH
  before_script:
    - apk add git
  script:
    # - npm ci # BUG: Cannot use this command because of this bug: https://github.com/npm/cli/issues/4828
    - npm install
    - npm run lint:fix || true
    - npm run format
    - git config user.name "GitLab CI"
    - git config user.email "ci.epitech@gmail.com"
    - git remote add gitlab_origin https://oauth2:$PUSH_GITLAB_ACCESS_TOKEN@gitlab.com/$CI_PROJECT_PATH.git || true
    - git add .
    - git diff-index --quiet HEAD || git commit -m "$COMMIT_MESSAGE"
    - git push gitlab_origin HEAD:$PUSH_BRANCH
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        PUSH_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

Lint:
  stage: test
  image: node:alpine
  needs:
    - job: Format code
      optional: true
  dependencies: []
  interruptible: true
  script:
    # - npm ci # BUG: Cannot use this command because of this bug: https://github.com/npm/cli/issues/4828
    - npm install
    - npm run lint
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^\d+(\.\d+)*/

Build:
  stage: test
  image: node:alpine
  needs:
    - job: Format code
      optional: true
  dependencies: []
  interruptible: true
  script:
    # - npm ci # BUG: Cannot use this command because of this bug: https://github.com/npm/cli/issues/4828
    - npm install
    - npm run build
  artifacts:
    paths:
      - .output/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^\d+(\.\d+)*/

# This job is used to let GitLab merge requests that have no job to be merged
# Fixing a weird behavior of GitLab, not letting you merge when your pipeline contains no job
No job MR validation:
  stage: test
  needs: []
  dependencies: []
  script:
    - echo "Skipping pipeline..."
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

Unit tests:
  stage: test
  image: node:alpine
  needs:
    - job: Format code
      optional: true
  dependencies: []
  script:
    # - npm ci # BUG: Cannot use this command because of this bug: https://github.com/npm/cli/issues/4828
    - npm install
    - npm run test:unit
  artifacts:
    paths:
      - junit-report.xml
    reports:
      junit: junit-report.xml
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^\d+(\.\d+)*/

E2E tests:
  stage: test
  image: cypress/base:latest
  needs:
    - job: Format code
      optional: true
    - job: Build
      artifacts: true
  script:
    # - npm ci # BUG: Cannot use this command because of this bug: https://github.com/npm/cli/issues/4828
    - npm install
    - npm run test:e2e:record
  artifacts:
    expire_in: 1 day
    paths:
      - cypress/videos/
      - cypress/screenshots/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^\d+(\.\d+)*/

pages:
  stage: deploy
  image: node:alpine
  needs:
    - job: Format code
      optional: true
    - job: Lint
      optional: true
    - job: Unit tests
      optional: true
    - job: E2E tests
      optional: true
  dependencies: []
  variables:
    SENTRY_AUTH_TOKEN: $CUSTOM_SENTRY_AUTH_TOKEN
    NUXT_SENTRY_RELEASE: $CI_COMMIT_TAG
  script:
    - cp ${PRODUCTION_ENV_FILE} .env
    - echo -e "\nNUXT_PUBLIC_VERSION=${CI_COMMIT_TAG}\n" >> .env
    # - npm ci # BUG: Cannot use this command because of this bug: https://github.com/npm/cli/issues/4828
    - npm install
    - npm run generate
  artifacts:
    paths:
      - .output/public
    expire_in: never
  publish: .output/public
  environment:
    name: production
    url: https://hervaud.fr
    deployment_tier: production
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+(\.\d+)*/
