// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface ConfigStoryblok {
  title?: string;
  component: "config";
  _uid: string;
  [k: string]: any;
}

export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | ConfigStoryblok
    | FeatureStoryblok
    | GridStoryblok
    | PageStoryblok
    | TeaserStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (ConfigStoryblok | FeatureStoryblok | GridStoryblok | PageStoryblok | TeaserStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}
