// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "@storyblok/js";
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext } from "../storyblok.d.ts";
export interface About {
  description: StoryblokRichtext;
  component: "about";
  _uid: string;
}

export interface Experience {
  startDate: string;
  endDate?: string;
  title: string;
  company: string;
  link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  role: string;
  tags?: {
    value: string[];
  };
  component: "experience";
  _uid: string;
}

export interface Profile {
  name: string;
  job: string;
  description: string;
  links?: SocialLink[];
  component: "profile";
  _uid: string;
}

export interface Project {
  title: string;
  link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  previewImage?: StoryblokAsset;
  summary: string;
  description: string;
  company?: string;
  year: string;
  tags?: {
    value: string[];
  };
  component: "project";
  _uid: string;
}

export interface ProjectsPreview {
  projects: (ISbStoryData<Project> | string)[];
  component: "projects-preview";
  _uid: string;
}

export interface SocialLink {
  name: string;
  url: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  icon: string;
  component: "social-link";
  _uid: string;
}
