version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - update-type: "version-update:semver-major"
      - update-type: "version-update:semver-minor"
    open-pull-requests-limit: 50
    labels:
      - dependencies
    assignees:
      - curs3_w4ll
