version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - update-types: ["version-update:semver-patch"]
      - dependency-name: "@rollup/rollup-*"
    open-pull-requests-limit: 50
    labels:
      - dependencies
    assignees:
      - curs3_w4ll
